[package]
name = "libarchive"
version = "0.1.0"
authors = ["Christian Krause <christian.krause@mailbox.org>"]
edition = "2018"

[dependencies]
libarchive-sys = { path = "../libarchive-sys" }

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
